'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DsPaymentType
    Inherits DataSet
    
    Private tablePayment_Type As Payment_TypeDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Payment Type")) Is Nothing) Then
                Me.Tables.Add(New Payment_TypeDataTable(ds.Tables("Payment Type")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Payment_Type As Payment_TypeDataTable
        Get
            Return Me.tablePayment_Type
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DsPaymentType = CType(MyBase.Clone,DsPaymentType)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("Payment Type")) Is Nothing) Then
            Me.Tables.Add(New Payment_TypeDataTable(ds.Tables("Payment Type")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tablePayment_Type = CType(Me.Tables("Payment Type"),Payment_TypeDataTable)
        If (Not (Me.tablePayment_Type) Is Nothing) Then
            Me.tablePayment_Type.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DsPaymentType"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DsPaymentType.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tablePayment_Type = New Payment_TypeDataTable
        Me.Tables.Add(Me.tablePayment_Type)
    End Sub
    
    Private Function ShouldSerializePayment_Type() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub Payment_TypeRowChangeEventHandler(ByVal sender As Object, ByVal e As Payment_TypeRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class Payment_TypeDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnDescription As DataColumn
        
        Private columnPayment_Type_ID As DataColumn
        
        Friend Sub New()
            MyBase.New("Payment Type")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property DescriptionColumn As DataColumn
            Get
                Return Me.columnDescription
            End Get
        End Property
        
        Friend ReadOnly Property Payment_Type_IDColumn As DataColumn
            Get
                Return Me.columnPayment_Type_ID
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As Payment_TypeRow
            Get
                Return CType(Me.Rows(index),Payment_TypeRow)
            End Get
        End Property
        
        Public Event Payment_TypeRowChanged As Payment_TypeRowChangeEventHandler
        
        Public Event Payment_TypeRowChanging As Payment_TypeRowChangeEventHandler
        
        Public Event Payment_TypeRowDeleted As Payment_TypeRowChangeEventHandler
        
        Public Event Payment_TypeRowDeleting As Payment_TypeRowChangeEventHandler
        
        Public Overloads Sub AddPayment_TypeRow(ByVal row As Payment_TypeRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddPayment_TypeRow(ByVal Description As String, ByVal Payment_Type_ID As String) As Payment_TypeRow
            Dim rowPayment_TypeRow As Payment_TypeRow = CType(Me.NewRow,Payment_TypeRow)
            rowPayment_TypeRow.ItemArray = New Object() {Description, Payment_Type_ID}
            Me.Rows.Add(rowPayment_TypeRow)
            Return rowPayment_TypeRow
        End Function
        
        Public Function FindByPayment_Type_ID(ByVal Payment_Type_ID As String) As Payment_TypeRow
            Return CType(Me.Rows.Find(New Object() {Payment_Type_ID}),Payment_TypeRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As Payment_TypeDataTable = CType(MyBase.Clone,Payment_TypeDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New Payment_TypeDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnDescription = Me.Columns("Description")
            Me.columnPayment_Type_ID = Me.Columns("Payment Type ID")
        End Sub
        
        Private Sub InitClass()
            Me.columnDescription = New DataColumn("Description", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDescription)
            Me.columnPayment_Type_ID = New DataColumn("Payment Type ID", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPayment_Type_ID)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnPayment_Type_ID}, true))
            Me.columnPayment_Type_ID.AllowDBNull = false
            Me.columnPayment_Type_ID.Unique = true
        End Sub
        
        Public Function NewPayment_TypeRow() As Payment_TypeRow
            Return CType(Me.NewRow,Payment_TypeRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New Payment_TypeRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(Payment_TypeRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.Payment_TypeRowChangedEvent) Is Nothing) Then
                RaiseEvent Payment_TypeRowChanged(Me, New Payment_TypeRowChangeEvent(CType(e.Row,Payment_TypeRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.Payment_TypeRowChangingEvent) Is Nothing) Then
                RaiseEvent Payment_TypeRowChanging(Me, New Payment_TypeRowChangeEvent(CType(e.Row,Payment_TypeRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.Payment_TypeRowDeletedEvent) Is Nothing) Then
                RaiseEvent Payment_TypeRowDeleted(Me, New Payment_TypeRowChangeEvent(CType(e.Row,Payment_TypeRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.Payment_TypeRowDeletingEvent) Is Nothing) Then
                RaiseEvent Payment_TypeRowDeleting(Me, New Payment_TypeRowChangeEvent(CType(e.Row,Payment_TypeRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovePayment_TypeRow(ByVal row As Payment_TypeRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class Payment_TypeRow
        Inherits DataRow
        
        Private tablePayment_Type As Payment_TypeDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tablePayment_Type = CType(Me.Table,Payment_TypeDataTable)
        End Sub
        
        Public Property Description As String
            Get
                Try 
                    Return CType(Me(Me.tablePayment_Type.DescriptionColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePayment_Type.DescriptionColumn) = value
            End Set
        End Property
        
        Public Property Payment_Type_ID As String
            Get
                Return CType(Me(Me.tablePayment_Type.Payment_Type_IDColumn),String)
            End Get
            Set
                Me(Me.tablePayment_Type.Payment_Type_IDColumn) = value
            End Set
        End Property
        
        Public Function IsDescriptionNull() As Boolean
            Return Me.IsNull(Me.tablePayment_Type.DescriptionColumn)
        End Function
        
        Public Sub SetDescriptionNull()
            Me(Me.tablePayment_Type.DescriptionColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class Payment_TypeRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As Payment_TypeRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As Payment_TypeRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As Payment_TypeRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
