'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DsTemSaleByItem
    Inherits DataSet
    
    Private tableTemSaleByItem As TemSaleByItemDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("TemSaleByItem")) Is Nothing) Then
                Me.Tables.Add(New TemSaleByItemDataTable(ds.Tables("TemSaleByItem")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property TemSaleByItem As TemSaleByItemDataTable
        Get
            Return Me.tableTemSaleByItem
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DsTemSaleByItem = CType(MyBase.Clone,DsTemSaleByItem)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("TemSaleByItem")) Is Nothing) Then
            Me.Tables.Add(New TemSaleByItemDataTable(ds.Tables("TemSaleByItem")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableTemSaleByItem = CType(Me.Tables("TemSaleByItem"),TemSaleByItemDataTable)
        If (Not (Me.tableTemSaleByItem) Is Nothing) Then
            Me.tableTemSaleByItem.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DsTemSaleByItem"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DsTemSaleByItem.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableTemSaleByItem = New TemSaleByItemDataTable
        Me.Tables.Add(Me.tableTemSaleByItem)
    End Sub
    
    Private Function ShouldSerializeTemSaleByItem() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub TemSaleByItemRowChangeEventHandler(ByVal sender As Object, ByVal e As TemSaleByItemRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TemSaleByItemDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnBarcode As DataColumn
        
        Private columnBillNo As DataColumn
        
        Private columnDescription As DataColumn
        
        Private columnQty As DataColumn
        
        Private columnSaleDate As DataColumn
        
        Private columnTotal As DataColumn
        
        Private columnUnitPrice As DataColumn
        
        Friend Sub New()
            MyBase.New("TemSaleByItem")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property BarcodeColumn As DataColumn
            Get
                Return Me.columnBarcode
            End Get
        End Property
        
        Friend ReadOnly Property BillNoColumn As DataColumn
            Get
                Return Me.columnBillNo
            End Get
        End Property
        
        Friend ReadOnly Property DescriptionColumn As DataColumn
            Get
                Return Me.columnDescription
            End Get
        End Property
        
        Friend ReadOnly Property QtyColumn As DataColumn
            Get
                Return Me.columnQty
            End Get
        End Property
        
        Friend ReadOnly Property SaleDateColumn As DataColumn
            Get
                Return Me.columnSaleDate
            End Get
        End Property
        
        Friend ReadOnly Property TotalColumn As DataColumn
            Get
                Return Me.columnTotal
            End Get
        End Property
        
        Friend ReadOnly Property UnitPriceColumn As DataColumn
            Get
                Return Me.columnUnitPrice
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As TemSaleByItemRow
            Get
                Return CType(Me.Rows(index),TemSaleByItemRow)
            End Get
        End Property
        
        Public Event TemSaleByItemRowChanged As TemSaleByItemRowChangeEventHandler
        
        Public Event TemSaleByItemRowChanging As TemSaleByItemRowChangeEventHandler
        
        Public Event TemSaleByItemRowDeleted As TemSaleByItemRowChangeEventHandler
        
        Public Event TemSaleByItemRowDeleting As TemSaleByItemRowChangeEventHandler
        
        Public Overloads Sub AddTemSaleByItemRow(ByVal row As TemSaleByItemRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddTemSaleByItemRow(ByVal Barcode As String, ByVal BillNo As String, ByVal Description As String, ByVal Qty As Integer, ByVal SaleDate As Date, ByVal Total As Decimal, ByVal UnitPrice As Decimal) As TemSaleByItemRow
            Dim rowTemSaleByItemRow As TemSaleByItemRow = CType(Me.NewRow,TemSaleByItemRow)
            rowTemSaleByItemRow.ItemArray = New Object() {Barcode, BillNo, Description, Qty, SaleDate, Total, UnitPrice}
            Me.Rows.Add(rowTemSaleByItemRow)
            Return rowTemSaleByItemRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As TemSaleByItemDataTable = CType(MyBase.Clone,TemSaleByItemDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New TemSaleByItemDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnBarcode = Me.Columns("Barcode")
            Me.columnBillNo = Me.Columns("BillNo")
            Me.columnDescription = Me.Columns("Description")
            Me.columnQty = Me.Columns("Qty")
            Me.columnSaleDate = Me.Columns("SaleDate")
            Me.columnTotal = Me.Columns("Total")
            Me.columnUnitPrice = Me.Columns("UnitPrice")
        End Sub
        
        Private Sub InitClass()
            Me.columnBarcode = New DataColumn("Barcode", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnBarcode)
            Me.columnBillNo = New DataColumn("BillNo", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnBillNo)
            Me.columnDescription = New DataColumn("Description", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDescription)
            Me.columnQty = New DataColumn("Qty", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQty)
            Me.columnSaleDate = New DataColumn("SaleDate", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSaleDate)
            Me.columnTotal = New DataColumn("Total", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTotal)
            Me.columnUnitPrice = New DataColumn("UnitPrice", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnUnitPrice)
        End Sub
        
        Public Function NewTemSaleByItemRow() As TemSaleByItemRow
            Return CType(Me.NewRow,TemSaleByItemRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New TemSaleByItemRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(TemSaleByItemRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.TemSaleByItemRowChangedEvent) Is Nothing) Then
                RaiseEvent TemSaleByItemRowChanged(Me, New TemSaleByItemRowChangeEvent(CType(e.Row,TemSaleByItemRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.TemSaleByItemRowChangingEvent) Is Nothing) Then
                RaiseEvent TemSaleByItemRowChanging(Me, New TemSaleByItemRowChangeEvent(CType(e.Row,TemSaleByItemRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.TemSaleByItemRowDeletedEvent) Is Nothing) Then
                RaiseEvent TemSaleByItemRowDeleted(Me, New TemSaleByItemRowChangeEvent(CType(e.Row,TemSaleByItemRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.TemSaleByItemRowDeletingEvent) Is Nothing) Then
                RaiseEvent TemSaleByItemRowDeleting(Me, New TemSaleByItemRowChangeEvent(CType(e.Row,TemSaleByItemRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveTemSaleByItemRow(ByVal row As TemSaleByItemRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TemSaleByItemRow
        Inherits DataRow
        
        Private tableTemSaleByItem As TemSaleByItemDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableTemSaleByItem = CType(Me.Table,TemSaleByItemDataTable)
        End Sub
        
        Public Property Barcode As String
            Get
                Try 
                    Return CType(Me(Me.tableTemSaleByItem.BarcodeColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTemSaleByItem.BarcodeColumn) = value
            End Set
        End Property
        
        Public Property BillNo As String
            Get
                Try 
                    Return CType(Me(Me.tableTemSaleByItem.BillNoColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTemSaleByItem.BillNoColumn) = value
            End Set
        End Property
        
        Public Property Description As String
            Get
                Try 
                    Return CType(Me(Me.tableTemSaleByItem.DescriptionColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTemSaleByItem.DescriptionColumn) = value
            End Set
        End Property
        
        Public Property Qty As Integer
            Get
                Try 
                    Return CType(Me(Me.tableTemSaleByItem.QtyColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTemSaleByItem.QtyColumn) = value
            End Set
        End Property
        
        Public Property SaleDate As Date
            Get
                Try 
                    Return CType(Me(Me.tableTemSaleByItem.SaleDateColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTemSaleByItem.SaleDateColumn) = value
            End Set
        End Property
        
        Public Property Total As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTemSaleByItem.TotalColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTemSaleByItem.TotalColumn) = value
            End Set
        End Property
        
        Public Property UnitPrice As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTemSaleByItem.UnitPriceColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTemSaleByItem.UnitPriceColumn) = value
            End Set
        End Property
        
        Public Function IsBarcodeNull() As Boolean
            Return Me.IsNull(Me.tableTemSaleByItem.BarcodeColumn)
        End Function
        
        Public Sub SetBarcodeNull()
            Me(Me.tableTemSaleByItem.BarcodeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsBillNoNull() As Boolean
            Return Me.IsNull(Me.tableTemSaleByItem.BillNoColumn)
        End Function
        
        Public Sub SetBillNoNull()
            Me(Me.tableTemSaleByItem.BillNoColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDescriptionNull() As Boolean
            Return Me.IsNull(Me.tableTemSaleByItem.DescriptionColumn)
        End Function
        
        Public Sub SetDescriptionNull()
            Me(Me.tableTemSaleByItem.DescriptionColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsQtyNull() As Boolean
            Return Me.IsNull(Me.tableTemSaleByItem.QtyColumn)
        End Function
        
        Public Sub SetQtyNull()
            Me(Me.tableTemSaleByItem.QtyColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSaleDateNull() As Boolean
            Return Me.IsNull(Me.tableTemSaleByItem.SaleDateColumn)
        End Function
        
        Public Sub SetSaleDateNull()
            Me(Me.tableTemSaleByItem.SaleDateColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTotalNull() As Boolean
            Return Me.IsNull(Me.tableTemSaleByItem.TotalColumn)
        End Function
        
        Public Sub SetTotalNull()
            Me(Me.tableTemSaleByItem.TotalColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsUnitPriceNull() As Boolean
            Return Me.IsNull(Me.tableTemSaleByItem.UnitPriceColumn)
        End Function
        
        Public Sub SetUnitPriceNull()
            Me(Me.tableTemSaleByItem.UnitPriceColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TemSaleByItemRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As TemSaleByItemRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As TemSaleByItemRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As TemSaleByItemRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
