//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace Translator_CS.LangaugeTranslator {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TranslateServiceSoap", Namespace="http://www.webservicex.net")]
    public partial class TranslateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TranslateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TranslateService() {
            this.Url = global::Translator_CS.Properties.Settings.Default.Translator_CS_LangaugeTranslator_TranslateService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TranslateCompletedEventHandler TranslateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webservicex.net/Translate", RequestNamespace="http://www.webservicex.net", ResponseNamespace="http://www.webservicex.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Translate(Language LanguageMode, string Text) {
            object[] results = this.Invoke("Translate", new object[] {
                        LanguageMode,
                        Text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TranslateAsync(Language LanguageMode, string Text) {
            this.TranslateAsync(LanguageMode, Text, null);
        }
        
        /// <remarks/>
        public void TranslateAsync(Language LanguageMode, string Text, object userState) {
            if ((this.TranslateOperationCompleted == null)) {
                this.TranslateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslateOperationCompleted);
            }
            this.InvokeAsync("Translate", new object[] {
                        LanguageMode,
                        Text}, this.TranslateOperationCompleted, userState);
        }
        
        private void OnTranslateOperationCompleted(object arg) {
            if ((this.TranslateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslateCompleted(this, new TranslateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net")]
    public enum Language {
        
        /// <remarks/>
        EnglishTOChinese,
        
        /// <remarks/>
        EnglishTOFrench,
        
        /// <remarks/>
        EnglishTOGerman,
        
        /// <remarks/>
        EnglishTOItalian,
        
        /// <remarks/>
        EnglishTOJapanese,
        
        /// <remarks/>
        EnglishTOKorean,
        
        /// <remarks/>
        EnglishTOPortuguese,
        
        /// <remarks/>
        EnglishTOSpanish,
        
        /// <remarks/>
        ChineseTOEnglish,
        
        /// <remarks/>
        FrenchTOEnglish,
        
        /// <remarks/>
        FrenchTOGerman,
        
        /// <remarks/>
        GermanTOEnglish,
        
        /// <remarks/>
        GermanTOFrench,
        
        /// <remarks/>
        ItalianTOEnglish,
        
        /// <remarks/>
        JapaneseTOEnglish,
        
        /// <remarks/>
        KoreanTOEnglish,
        
        /// <remarks/>
        PortugueseTOEnglish,
        
        /// <remarks/>
        RussianTOEnglish,
        
        /// <remarks/>
        SpanishTOEnglish,
        
        /// <remarks/>
        SpanishToFrench,
        
        /// <remarks/>
        PortugueseToFrench,
        
        /// <remarks/>
        ItalianToFrench,
        
        /// <remarks/>
        GreekToFrench,
        
        /// <remarks/>
        GermanToFrench,
        
        /// <remarks/>
        FrenchToGreek,
        
        /// <remarks/>
        FrenchToItalian,
        
        /// <remarks/>
        FrenchToPortuguese,
        
        /// <remarks/>
        FrenchToDutch,
        
        /// <remarks/>
        FrenchToSpanish,
        
        /// <remarks/>
        EnglishToRussian,
        
        /// <remarks/>
        EnglishToDutch,
        
        /// <remarks/>
        DutchToEnglish,
        
        /// <remarks/>
        DutchToFrench,
        
        /// <remarks/>
        GreekToEnglish,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void TranslateCompletedEventHandler(object sender, TranslateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TranslateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591