'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
'
Namespace TranslatorWebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TranslateServiceSoap", [Namespace]:="http://www.webservicex.net")>  _
    Partial Public Class TranslateService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private TranslateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Translator_VB.My.MySettings.Default.Translator_VB_TranslatorWebService_TranslateService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event TranslateCompleted As TranslateCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webservicex.net/Translate", RequestNamespace:="http://www.webservicex.net", ResponseNamespace:="http://www.webservicex.net", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Translate(ByVal LanguageMode As Language, ByVal Text As String) As String
            Dim results() As Object = Me.Invoke("Translate", New Object() {LanguageMode, Text})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TranslateAsync(ByVal LanguageMode As Language, ByVal Text As String)
            Me.TranslateAsync(LanguageMode, Text, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TranslateAsync(ByVal LanguageMode As Language, ByVal Text As String, ByVal userState As Object)
            If (Me.TranslateOperationCompleted Is Nothing) Then
                Me.TranslateOperationCompleted = AddressOf Me.OnTranslateOperationCompleted
            End If
            Me.InvokeAsync("Translate", New Object() {LanguageMode, Text}, Me.TranslateOperationCompleted, userState)
        End Sub
        
        Private Sub OnTranslateOperationCompleted(ByVal arg As Object)
            If (Not (Me.TranslateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TranslateCompleted(Me, New TranslateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.webservicex.net")>  _
    Public Enum Language
        
        '''<remarks/>
        EnglishTOChinese
        
        '''<remarks/>
        EnglishTOFrench
        
        '''<remarks/>
        EnglishTOGerman
        
        '''<remarks/>
        EnglishTOItalian
        
        '''<remarks/>
        EnglishTOJapanese
        
        '''<remarks/>
        EnglishTOKorean
        
        '''<remarks/>
        EnglishTOPortuguese
        
        '''<remarks/>
        EnglishTOSpanish
        
        '''<remarks/>
        ChineseTOEnglish
        
        '''<remarks/>
        FrenchTOEnglish
        
        '''<remarks/>
        FrenchTOGerman
        
        '''<remarks/>
        GermanTOEnglish
        
        '''<remarks/>
        GermanTOFrench
        
        '''<remarks/>
        ItalianTOEnglish
        
        '''<remarks/>
        JapaneseTOEnglish
        
        '''<remarks/>
        KoreanTOEnglish
        
        '''<remarks/>
        PortugueseTOEnglish
        
        '''<remarks/>
        RussianTOEnglish
        
        '''<remarks/>
        SpanishTOEnglish
        
        '''<remarks/>
        SpanishToFrench
        
        '''<remarks/>
        PortugueseToFrench
        
        '''<remarks/>
        ItalianToFrench
        
        '''<remarks/>
        GreekToFrench
        
        '''<remarks/>        GermanToFrench
        
        '''<remarks/>
        FrenchToGreek
        
        '''<remarks/>
        FrenchToItalian
        
        '''<remarks/>
        FrenchToPortuguese
        
        '''<remarks/>
        FrenchToDutch
        
        '''<remarks/>
        FrenchToSpanish
        
        '''<remarks/>
        EnglishToRussian
        
        '''<remarks/>
        EnglishToDutch
        
        '''<remarks/>
        DutchToEnglish
        
        '''<remarks/>
        DutchToFrench
        
        '''<remarks/>
        GreekToEnglish
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub TranslateCompletedEventHandler(ByVal sender As Object, ByVal e As TranslateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TranslateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
