
/* DEO OPTIMO MAXIMO */
/*...................*/

/* AUTHOR		: Pandian S
   DEVELOPED		: 26-AUG-2006 
   PURPOSE		: Loading data in ComboBox without any Re-Load / Refresh / Freeze the Page 	 
   ARE			: ASP.NET 1.x 
   REQUIREMENT		: 1.70 MB */
  
/* SCRIPT FOR CREATING DATABASE NAMED 'INDIA' */
USE master
GO
SET NOCOUNT ON
GO
IF EXISTS(SELECT NAME FROM SYSDATABASES WHERE NAME ='india')
DROP DATABASE india
GO
CREATE DATABASE India
ON 
( NAME = India_Dat,
   FILENAME = 'C:\India_Dat.mdf')
LOG ON
( NAME = 'India_log',
   FILENAME = 'C:\India_Dat.ldf')
GO

--................................................................................
USE India
Go
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[States]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[States]
GO
CREATE TABLE [dbo].[States]
(
	[StateID] [int] NULL ,
	[Description] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Districts] [int] NULL 
) ON [PRIMARY]
GO
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[Districts]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[Districts]
GO
CREATE TABLE [dbo].[Districts]
(
	[DistrictID] [int] NULL ,
	[Description] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
) ON [PRIMARY]
GO
/*** Scripts for 'STATES' ***/
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(1,'Andaman and Nicobar',2)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(2,'Andhra Pradesh',23)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(3,'Arunachal Pradesh',16)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(4,'Assam',23)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(5,'Bihar',37)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(6,'Chandigarh',1)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(7,'Chhattisgarh',16)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(8,'Dadra and Nagar Haveli',1)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(9,'Daman and Diu',2)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(10,'Delhi',9)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(11,'Goa',2)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(12,'Gujarat',25)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(13,'Haryana',20)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(14,'Himachal Pradesh',12)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(15,'Jammu and Kashmir',14)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(16,'Jharkhand',22)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(17,'Karnataka',27)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(18,'Kerala',14)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(19,'Lakshadweep',1)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(20,'Madhya Pradesh',48)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(21,'Maharashtra',35)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(22,'Manipur',9)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(23,'Meghalaya',7)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(24,'Mizoram',8)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(25,'Nagaland',8)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(26,'Orissa',30)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(27,'Pondicherry',4)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(28,'Punjab',17)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(29,'Rajasthan',32)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(30,'Sikkim',40)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(31,'Tamil Nadu',30)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(32,'Tripura',4)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(33,'Uttar Pradesh',70)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(34,'Uttaranchal',13)
INSERT INTO [States] ([StateID],[Description],[Districts])VALUES(35,'West Bengal',18)
--...........................................................................................
GO
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(1,'Andaman')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(1,'Nicobar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Adilabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Cuddapah')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Hyderabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Krishna')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Medak')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Nizamabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Srikakulam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Warangal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Anantapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'East Godavari')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Karimnagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Kurnool')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Nalgonda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Prakasam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Visakhapatnam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'West Godavari')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Chittoor')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Guntur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Khammam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Mahbubnagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Nellore')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Rangareddi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(2,'Vizianagaram')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Anjaw')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'East Kameng')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Lohit')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Papum Pare')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Upper Siang')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Changlang')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'East Siang')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Lower Dibang Valley')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Tawang')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Upper Subansiri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Dibang Valley')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Kurung Kumey')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Lower Subansiri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'Tirap')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(3,'West Kameng')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Barpeta')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Darrang')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Dibrugarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Hailakandi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Karbi Anglong')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Lakhimpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Nalbari')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Sonitpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Bongaigaon')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Dhemaji')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Goalpara')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Jorhat')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Karimganj')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Marigaon')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'North Cachar Hills')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Tinsukia')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Cachar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Dhubri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Golaghat')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Kamrup')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Kokrajhar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Nagaon')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(4,'Sivasagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Araria')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Begusarai')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Buxar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Gaya')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Jehanabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Khagaria')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Madhepura')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Muzaffarpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Patna')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Saharsa')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Sheikhpura')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Siwan')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'West Champaran')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Aurangabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Bhagalpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Darbhanga')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Gopalganj')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Kaimur (Bhabua)')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Kishanganj')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Madhubani')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Nalanda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Purnia')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Samastipur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Sheohar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(5,'Supaul')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(6,'Chandigarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Bastar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Dhamtari')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Jashpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Korba')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Raigarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Surguja')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Bilaspur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Durg')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Kanker')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Korea')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Raipur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Dantewada')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Janjgir-Champa')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Kawardha')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Mahasamund')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(7,'Rajnandgaon')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(8,'Dadra & Nagar Haveli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(9,'Daman')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(9,'Diu')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(10,'Central Delhi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(10,'North Delhi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(10,'South Delhi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(10,'East Delhi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(10,'North East Delhi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(10,'South West Delhi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(10,'New Delhi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(10,'North West Delhi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(10,'West Delhi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(11,'North Goa')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(11,'South Goa')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Ahmedabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Banas Kantha')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Dahod')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Junagadh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Mahesana')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Panch Mahals')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Rajkot')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Surendranagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Valsad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Amreli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Bharuch')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Gandhinagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Kachchh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Narmada')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Patan')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Sabar Kantha')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'The Dangs')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Anand')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Bhavnagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Jamnagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Kheda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Navsari')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Porbandar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Surat')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(12,'Vadodara')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Ambala')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Fatehabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Jhajjar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Karnal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Mewat')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Rewari')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Sonipat')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Bhiwani')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Gurgaon')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Jind')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Kurukshetra')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Panchkula')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Rohtak')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Yamunanagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Faridabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(30,'North Sikkim')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(30,'South Sikkim')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Chennai')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Dharmapuri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Kanchipuram')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Krishnagiri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Namakkal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Pudukkottai')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Sivaganga')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Thoothukudi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Tiruvallur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Vellore')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Coimbatore')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Dindigul')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Kanyakumari')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Madurai')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Nilgiris')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Ramanathapuram')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Thanjavur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Tiruchirappalli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Tiruvannamalai')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Viluppuram')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Cuddalore')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Erode')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Karur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Nagapattinam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Perambalur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Salem')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Theni')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Tirunelveli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Tiruvarur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(31,'Virudhunagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(32,'Dhalai')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(32,'West Tripura')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(32,'North Tripura')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(32,'South Tripura')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Agra')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Ambedkar Nagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Bagpat')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Balrampur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Bareilly')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Budaun')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Chitrakoot')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Etawah')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Fatehpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Ghaziabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Gorakhpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Hathras')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Jhansi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Kanpur Dehat')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Kheri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Lucknow')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Mainpuri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Meerut')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Muzaffarnagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'RaeBareli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Sant Kabir Nagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Shravasti')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Sonbhadra')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Aligarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Auraiya')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Bahraich')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Banda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Basti')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Bulandshahr')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Deoria')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Faizabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Firozabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Ghazipur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Hamirpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Jalaun')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Jyotiba Phule Nagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Kanpur Nagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Kushinagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Maharajganj')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Mathura')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Mirzapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Pilibhit')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Rampur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Sant Ravidas Nagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Siddharthnagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Sultanpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Allahabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Azamgarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Ballia')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Barabanki')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Bijnor')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Chandauli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Etah')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Farrukhabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Gautam Buddha Nagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Gonda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Hardoi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Jaunpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Kannauj')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Kaushambi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Lalitpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Mahoba')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Mau')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Moradabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Pratapgarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Saharanpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Shahjahanpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Sitapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(33,'Unnao')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Almora')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Champawat')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Nainital')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Rudraprayag')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Uttarkashi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Bageshwar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Dehradun')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Pauri Garhwal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Tehri Garhwal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Chamoli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Haridwar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Pithoragarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(34,'Udham Singh Nagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Bankura')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Cooch Behar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Hooghly')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Malda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'North 24 Parganas')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'South 24 Parganas')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Bardhaman')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Darjiling')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Howrah')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Murshidabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'North Dinajpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'South Dinajpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Birbhum')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'East Midnapore')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Jalpaiguri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Nadia')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'Puruliya')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(35,'West Midnapore')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Hisar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Kaithal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Mahendragarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Panipat')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(13,'Sirsa')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Bilaspur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Kangra')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Lahaul & Spiti')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Sirmaur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Chamba')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Kinnaur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Mandi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Solan')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Hamirpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Kullu')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Shimla')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(14,'Una')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Anantnag')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Doda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Kathua')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Poonch')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Srinagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Baramulla')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Jammu')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Kupwara')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Pulwama')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Udhampur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Budgam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Kargil')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Leh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(15,'Rajauri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Bokaro')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Dhanbad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Garhwa')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Gumla')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Koderma')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Pakur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Sahibganj')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'West Singhbhum')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Chatra')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Dumka')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Giridih')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Hazaribag')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Latehar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Palamu')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Seraikela')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Deoghar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'East Singhbhum')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Godda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Jamtara')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Lohardaga')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Ranchi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(16,'Simdega')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Bagalkot')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Belgaum')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Bijapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Chitradurga')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Gadag')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Haveri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Koppal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'North Kannada')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'South Kannada')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Bangalore')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Bellary')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Chamrajnagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Davangere')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Gulbarga')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Kodagu')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Mandya')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Raichur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Tumkur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Bangalore Rural')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Bidar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Chickmagalur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Dharwad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Hassan')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Kolar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Mysore')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Shimoga')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(17,'Udupi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Alappuzha')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Kannur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Kottayam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Palakkad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Thrissur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Ernakulam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Kasargod')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Kozhikode')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Pathanamthitta')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Wayanad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Idukki')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Kollam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Malappuram')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(18,'Thiruvananthapuram')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(19,'Lakshadweep')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Anuppur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Ashoknagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Balaghat')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Barwani')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Betul')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Bhind')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Bhopal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Burhanpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Chhatarpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Chhindwara')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Damoh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Datia')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Dewas')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Dhar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Dindori')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Guna')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Gwalior')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Harda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Hoshangabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Indore')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Jabalpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Jhabua')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Katni')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Khandwa')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Khargone')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Mandla')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Mandsaur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Morena')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Narsinghpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Neemuch')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Panna')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Raisen')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Rajgarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Ratlam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Rewa')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Sagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Satna')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Sehore')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Seoni')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Shahdol')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Shajapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Sheopur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Shivpuri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Sidhi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Tikamgarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Ujjain')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Umaria')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(20,'Vidisha')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Ahmednagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Aurangabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Bhandara')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Dhule')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Hingoli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Kolhapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Nagpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Nashik')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Pune')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Sangli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Solapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Washim')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Akola')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Bandra Suburban')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Buldhana')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Gadchiroli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Jalgaon')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Latur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Nanded')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Osmanabad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Raigad')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Satara')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Thane')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Yavatmal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Amravati')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Beed')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Chandrapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Gondia')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Jalna')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Mumbai')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Nandurbar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Parbhani')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Ratnagiri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Sindhudurg')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(21,'Wardha')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(22,'Bishnupur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(22,'Imphal East')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(22,'Tamenglong')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(22,'Chandel')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(22,'Imphal West')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(22,'Thoubal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(22,'Churachandpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(22,'Senapati')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(22,'Ukhrul')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(23,'East Garo Hills')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(23,'Ri Bhoi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(23,'West Khasi Hills')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(23,'East Khasi Hills')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(23,'South Garo Hills')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(23,'Jaintia Hills')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(23,'West Garo Hills')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(24,'Aizawl')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(24,'Lawngtlai')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(24,'Saiha')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(24,'Champhai')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(24,'Lunglei')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(24,'Serchhip')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(24,'Kolasib')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(24,'Mamit')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(25,'Dimapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(25,'Mon')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(25,'Wokha')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(25,'Kohima')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(25,'Phek')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(25,'Zunheboto')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(25,'Mokokchung')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(25,'Tuensang')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Angul')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Bargarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Cuttack')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Gajapati')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Jajapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Kandhamal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Khordha')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Mayurbhanj')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Nuapada')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Sambalpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Balangir')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Bhadrak')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Debagarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Ganjam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Jharsuguda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Kendrapara')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Koraput')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Nabarangapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Puri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Subarnapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Baleswar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Boudh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Dhenkanal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Jagatsinghapur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Kalahandi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Kendujhar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Malkangiri')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Nayagarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Rayagada')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(26,'Sundergarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(27,'Karaikal')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(27,'Yanam')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(27,'Mahe')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(27,'Pondicherry')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Amritsar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Fatehgarh Sahib')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Hoshiarpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Ludhiana')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Muktsar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Rupnagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Bathinda')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Ferozepur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Jalandhar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Mansa')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Nawanshahr')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Sangrur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Faridkot')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Gurdaspur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Kapurthala')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Moga')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(28,'Patiala')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Ajmer')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Baran')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Bhilwara')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Chittorgarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Dholpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Jaipur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Jhalawar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Karauli')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Pali')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Sikar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Tonk')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Alwar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Barmer')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Bikaner')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Churu')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Dungarpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Jaisalmer')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Jhunjhunu')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Kota')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Rajsamand')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Sirohi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Udaipur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Banswara')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Bharatpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Bundi')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Dausa')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Hanumangarh')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Jalor')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Jodhpur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Nagaur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Sawai Madhopur')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(29,'Sri Ganganagar')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(30,'East Sikkim')
INSERT INTO [Districts] ([DistrictID],[Description])VALUES(30,'West Sikkim')
--.......................................................................................
