//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace setup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("setup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connectionString=Data Source=127.0.0.1\SQLEXPRESS;Initial Catalog=&apos;SDASDB&apos;;integrated security = true
        ///.
        /// </summary>
        internal static string AConfig {
            get {
                return ResourceManager.GetString("AConfig", resourceCulture);
            }
        }
        
        internal static byte[] AxInterop_ShockwaveFlashObjects {
            get {
                object obj = ResourceManager.GetObject("AxInterop_ShockwaveFlashObjects", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DoorServer {
            get {
                object obj = ResourceManager.GetObject("DoorServer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Interop_ShockwaveFlashObjects {
            get {
                object obj = ResourceManager.GetObject("Interop_ShockwaveFlashObjects", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IrisSkin2 {
            get {
                object obj = ResourceManager.GetObject("IrisSkin2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] myfile {
            get {
                object obj = ResourceManager.GetObject("myfile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connectionString=Data Source=localhost\SQLEXPRESS;initial catalog=SDASDB;integrated security=true
        ///mainPortNumber=5000
        ///UpdatesPort=5001
        ///sendUpdatesEvery=60000
        ///.
        /// </summary>
        internal static string SConfig {
            get {
                return ResourceManager.GetString("SConfig", resourceCulture);
            }
        }
        
        internal static byte[] Smart_Door_Administration {
            get {
                object obj = ResourceManager.GetObject("Smart_Door_Administration", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SmartDoor {
            get {
                object obj = ResourceManager.GetObject("SmartDoor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SQLDMO {
            get {
                object obj = ResourceManager.GetObject("SQLDMO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] uninstall {
            get {
                object obj = ResourceManager.GetObject("uninstall", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
