//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyMenu.rc
//
#define IDM_FILE_OPEN                   100
#define IDR_MENU1                       101
#define IDM_FILE_SAVE                   101
#define IDM_FILE_EXIT                   102
#define IDB_BITMAP1                     102
#define IDM_DRAW_LINE                   103
#define IDI_ICON1                       103
#define IDM_DRAW_CIRCLE                 104
#define IDM_DRAW_ELLIPSE                105
#define IDM_DRAW_RECTANGLE              106
#define IDC_NODROP                      106
#define IDM_COLOR_RED                   107
#define IDM_COLOR_GREEN                 108
#define IDC_CURSOR1                     108
#define IDM_COLOR_BLACK                 109
#define IDI_ICON2                       109
#define IDM_COLOR_CHOOSE                110
#define IDM_HELP_ABOUT                  111
#define IDI_ICON3                       111
#define IDM_HELP_CONTENT                112
#define IDM_FILE_NEW                    113
#define IDM_DRAW_FILL                   114
#define IDM_COLOR_BLUE                  115
#define IDM_DRAW_SQUARE                 116
#define IDM_VIEW_TOOLBOX                117
#define IDC_BUTTON1                     1000
#define IDC_LINE                        1000
#define IDC_BUTTON2                     1001
#define IDC_CIRCLE                      1001
#define IDC_BUTTON3                     1002
#define IDC_RECT                        1002
#define IDC_BUTTON4                     1003
#define IDC_ELLIPSE                     1003
#define IDC_BUTTON5                     1004
#define IDC_SQUARE                      1004
#define IDC_BUTTON6                     1005
#define IDC_COLOR                       1005
#define IDC_BUTTON7                     1006
#define IDC_FILL                        1006
#define IDC_BUTTON8                     1007
#define IDC_BUTTON9                     1008
#define IDC_BUTTON10                    1009
#define IDC_BUTTON11                    1010
#define IDC_BUTTON12                    1011
#define IDD_DIALOGBAR                   1110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
