//
// Decompiled with: Decompiler.NET, Version=2.0.0.230, Culture=neutral, PublicKeyToken=null, Version: 2.0.0.230
// Decompilation Started at: 19/12/2006 04:48:51 ?
// Copyright 2003 - 2004, Jungle Creatures, Inc., All Rights Reserved. http://www.junglecreatures.com/
// Written by Jonathan Pierce, Email: support@junglecreatures.com
//

namespace Sunisoft.IrisSkin

{
		
		#region Namespace Import Declarations
		
			using ad;
			using System.Reflection;
			using System;
			
		#endregion
		
	public class Consts
	
	{
		
		#region Fields
			public const string SKIN2_BOTTOMBORDERNEEDREGION = "SKIN2_BOTTOMBORDERNEEDREGION";
			public const string SKIN2_BOTTOMBORDERTHREESECT = "SKIN2_BOTTOMBORDERTHREESECT";
			public const string SKIN2_BOTTOMREGIONMAXY = "SKIN2_BOTTOMREGIONMAXY";
			public const string SKIN2_BOTTOMREGIONMINY = "SKIN2_BOTTOMREGIONMINY";
			public const string SKIN2_BUTTON = "SKIN2_BUTTON";
			public const string SKIN2_BUTTONFONTCOLOR = "SKIN2_BUTTONFONTCOLOR";
			public const string SKIN2_CHECKBOX = "SKIN2_CHECKBOX";
			public const string SKIN2_CHECKBOXLIST = "SKIN2_CHECKBOXLIST";
			public const string SKIN2_CHECKEDMENUICON = "SKIN2_CHECKEDMENUICON";
			public const string SKIN2_CONTROLBORDERCOLOR = "SKIN2_CONTROLBORDERCOLOR";
			public const string SKIN2_CONTROLCOLOR = "SKIN2_CONTROLCOLOR";
			public const string SKIN2_CONTROLFONTCOLOR = "SKIN2_CONTROLFONTCOLOR";
			public const string SKIN2_FORMBOTTOMBORDER1 = "SKIN2_FORMBOTTOMBORDER1";
			public const string SKIN2_FORMBOTTOMBORDER2 = "SKIN2_FORMBOTTOMBORDER2";
			public const string SKIN2_FORMBOTTOMBORDER3 = "SKIN2_FORMBOTTOMBORDER3";
			public const string SKIN2_FORMCOLOR = "SKIN2_FORMCOLOR";
			public const string SKIN2_FORMLEFTBORDER = "SKIN2_FORMLEFTBORDER";
			public const string SKIN2_FORMRIGHTBORDER = "SKIN2_FORMRIGHTBORDER";
			public const string SKIN2_LEFTBARENDCOLOR = "SKIN2_LEFTBARENDCOLOR";
			public const string SKIN2_LEFTBARSTARTCOLOR = "SKIN2_LEFTBARSTARTCOLOR";
			public const string SKIN2_MENUBAR = "SKIN2_MENUBAR";
			public const string SKIN2_MENUBARENDCOLOR = "SKIN2_MENUBARENDCOLOR";
			public const string SKIN2_MENUBARSTARTCOLOR = "SKIN2_MENUBARSTARTCOLOR";
			public const string SKIN2_MENUITEMCOLOR = "SKIN2_MENUITEMCOLOR";
			public const string SKIN2_MENUITEMFONTCOLOR = "SKIN2_MENUITEMFONTCOLOR";
			public const string SKIN2_MINIMIZEDTITLE = "SKIN2_MINIMIZEDTITLE";
			public const string SKIN2_PROGRESSBAR1 = "SKIN2_PROGRESSBAR1";
			public const string SKIN2_PROGRESSBAR2 = "SKIN2_PROGRESSBAR2";
			public const string SKIN2_PROGRESSBAR3 = "SKIN2_PROGRESSBAR3";
			public const string SKIN2_PROGRESSBAR4 = "SKIN2_PROGRESSBAR4";
			public const string SKIN2_RADIOBUTTON = "SKIN2_RADIOBUTTON";
			public const string SKIN2_SCROLLBAR = "SKIN2_SCROLLBAR";
			public const string SKIN2_SCROLLBARCOLOR = "SKIN2_SCROLLBARCOLOR";
			public const string SKIN2_SCROLLBARDOWNBUTTON = "SKIN2_SCROLLBARDOWNBUTTON";
			public const string SKIN2_SCROLLBARUPBUTTON = "SKIN2_SCROLLBARUPBUTTON";
			public const string SKIN2_SCROLLBUTTON = "SKIN2_SCROLLBUTTON";
			public const string SKIN2_SELECTEDMENUBORDERCOLOR = "SKIN2_SELECTEDMENUBORDERCOLOR";
			public const string SKIN2_SELECTEDMENUCOLOR = "SKIN2_SELECTEDMENUCOLOR";
			public const string SKIN2_SELECTEDMENUFONTCOLOR = "SKIN2_SELECTEDMENUFONTCOLOR";
			public const string SKIN2_SIDECHANNELBAR = "SKIN2_SIDECHANNELBAR";
			public const string SKIN2_SIDECHANNELBORDERCOLOR = "SKIN2_SIDECHANNELBORDERCOLOR";
			public const string SKIN2_SIDECHANNELCOLOR = "SKIN2_SIDECHANNELCOLOR";
			public const string SKIN2_SIDECHANNELTITLE = "SKIN2_SIDECHANNELTITLE";
			public const string SKIN2_TABCONTROL = "SKIN2_TABCONTROL";
			public const string SKIN2_TABCONTROLACTIVEFONTCOLOR = "SKIN2_TABCONTROLACTIVEFONTCOLOR";
			public const string SKIN2_TABCONTROLBORDERCOLOR = "SKIN2_TABCONTROLBORDERCOLOR";
			public const string SKIN2_TABCONTROLCOLOR = "SKIN2_TABCONTROLCOLOR";
			public const string SKIN2_TABCONTROLINACTIVEFONTCOLOR = "SKIN2_TABCONTROLINACTIVEFONTCOLOR";
			public const string SKIN2_TABCONTROLLINE = "SKIN2_TABCONTROLLINE";
			public const string SKIN2_TITLEBAR1 = "SKIN2_TITLEBAR1";
			public const string SKIN2_TITLEBAR2 = "SKIN2_TITLEBAR2";
			public const string SKIN2_TITLEBAR3 = "SKIN2_TITLEBAR3";
			public const string SKIN2_TITLEBAR4 = "SKIN2_TITLEBAR4";
			public const string SKIN2_TITLEBAR5 = "SKIN2_TITLEBAR5";
			public const string SKIN2_TITLEBARBUTTONPOSX = "SKIN2_TITLEBARBUTTONPOSX";
			public const string SKIN2_TITLEBARBUTTONPOSY = "SKIN2_TITLEBARBUTTONPOSY";
			public const string SKIN2_TITLEBARCAPTIONTOP = "SKIN2_TITLEBARCAPTIONTOP";
			public const string SKIN2_TITLEBARICONPOSX = "SKIN2_TITLEBARICONPOSX";
			public const string SKIN2_TITLEBARICONPOSY = "SKIN2_TITLEBARICONPOSY";
			public const string SKIN2_TITLEBARNEEDREGION = "SKIN2_TITLEBARNEEDREGION";
			public const string SKIN2_TITLEBARREGIONMAXY = "SKIN2_TITLEBARREGIONMAXY";
			public const string SKIN2_TITLEBARREGIONMINY = "SKIN2_TITLEBARREGIONMINY";
			public const string SKIN2_TITLEBUTTONS = "SKIN2_TITLEBUTTONS";
			public const string SKIN2_TITLEFIVESECT = "SKIN2_TITLEFIVESECT";
			public const string SKIN2_TITLEFONTCOLOR = "SKIN2_TITLEFONTCOLOR";
			public const string SKIN2_TOOLBAR = "SKIN2_TOOLBAR";
			public const string SKIN2_TOOLBARBORDERCOLOR = "SKIN2_TOOLBARBORDERCOLOR";
			public const string SKIN2_TOOLBARDOWNCOLOR = "SKIN2_TOOLBARDOWNCOLOR";
			public const string SKIN2_TOOLBARENDCOLOR = "SKIN2_TOOLBARENDCOLOR";
			public const string SKIN2_TOOLBARONCOLOR = "SKIN2_TOOLBARONCOLOR";
			public const string SKIN2_TOOLBARSTARTCOLOR = "SKIN2_TOOLBARSTARTCOLOR";
			public const string SKIN2_TOPMENUFONTCOLOR = "SKIN2_TOPMENUFONTCOLOR";
			public const string SKIN2_TOPSELECTEDMENUBORDERCOLOR = "SKIN2_TOPSELECTEDMENUBORDERCOLOR";
			public const string SKIN2_TOPSELECTEDMENUCOLOR = "SKIN2_TOPSELECTEDMENUCOLOR";
			public const string SKIN2_TOPSELECTEDMENUFONTCOLOR = "SKIN2_TOPSELECTEDMENUFONTCOLOR";
			public const string SKIN2_TRACKBAR = "SKIN2_TRACKBAR";
			public const string SKIN2_TRACKBARSLIDER = "SKIN2_TRACKBARSLIDER";
			public const string SKIN2_TRACKBARVSLIDER = "SKIN2_TRACKBARVSLIDER";
			public const string SKIN2_TRANSCOLOR = "SKIN2_TRANSCOLOR";
		#endregion
		
		#region Constructors
		
			private Consts ()
			/*
				// Code Size: 7 Bytes
				.maxstack 9
				L_0000: ldarg.0 
				L_0001: call System.Object::Void .ctor()
				L_0006: ret 
			*/
		#endregion
	}
	
}

