(function(){
var f=document,j=navigator,l=window;function da(){var b=f.cookie,a=Math.round((new Date).getTime()/1000),c=b.indexOf("__utma=")>-1,e=b.indexOf("__utmb=")>-1,d=b.indexOf("__utmc=")>-1,g,i={};if(c){g=b.split("__utma=")[1].split(";")[0].split(".");i.sid=(!e||!d?a:g[4])+"";i.vid=g[1]+"."+g[2];i.from_cookie=true}else{i.sid=l&&l.gaGlobal&&l.gaGlobal.sid?l.gaGlobal.sid:a+"";i.vid=l&&l.gaGlobal&&l.gaGlobal.vid?l.gaGlobal.vid:(n()^ea())*2147483647+"."+a;i.from_cookie=false}i.hid=l&&l.gaGlobal&&l.gaGlobal.hid?
l.gaGlobal.hid:n();l.gaGlobal=i;return i}function n(){return Math.round(Math.random()*2147483647)}function ea(){var b=f.cookie?f.cookie:"",a=l.history.length,c,e,d=[j.appName,j.version,j.language?j.language:j.browserLanguage,j.platform,j.userAgent,j.javaEnabled()?1:0].join("");if(l.screen)d+=l.screen.width+"x"+l.screen.height+l.screen.colorDepth;else if(l.java){e=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=e.screen.width+"x"+e.screen.height}d+=b;d+=f.referrer?f.referrer:"";c=d.length;
while(a>0)d+=a--^c++;return fa(d)}function fa(b){var a=1,c=0,e,d;if(!(b==undefined||b=="")){a=0;for(e=b.length-1;e>=0;e--){d=b.charCodeAt(e);a=(a<<6&268435455)+d+(d<<14);c=a&266338304;a=c!=0?a^c>>21:a}}return a};var s={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",google_contents:"contents",
google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_gl:"gl",google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",
google_language:"hl",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui"},u={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",
google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_page_url:"url",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"};function A(b){return s[b]||u[b]||null};function B(){}B.prototype.c=function(){};B.prototype.e=function(){};B.prototype.o=function(){};var E=null;function G(){this.b=this.m();this.g=false;if(!this.b){this.g=this.i();if(!this.g)E.e("Browser does not allow cookies")}}G.prototype.f="__gads=";G.prototype.d="GoogleAdServingTest=";G.prototype.l=function(){return this.b};G.prototype.setCookieInfo=function(b){this.a=b._cookies_[0];if(this.a!=null){this.b=this.a._value_;this.n()}};G.prototype.k=function(b){var a=(new Date).valueOf(),c=new Date;
c.setTime(a+b);return c};G.prototype.j=function(b){if(this.b!=null||!this.g){E.c("Skipping fetch cookie call");return}var a=document.domain,c="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+H(b)+"&domain="+H(a);E.c("Issuing a fetch cookie call with <a href='"+c+"'>"+c+"</a>");document.write("<script src = '"+c+"'><\/script>")};G.prototype.i=function(){document.cookie=this.d+"Good";var b=this.h(this.d),a=b=="Good";if(a){var c=this.k(-1);
document.cookie=this.d+"; expires="+c.toGMTString()}return a};G.prototype.m=function(){var b=this.h(this.f);if(b!=null)E.c("Read first party cookie: "+b);else E.e("No first party cookie found");return b};G.prototype.h=function(b){var a=document.cookie,c=a.indexOf(b),e=null;if(c!=-1){var d=c+b.length,g=a.indexOf(";",d);if(g==-1)g=a.length;e=a.substring(d,g)}return e};G.prototype.n=function(){if(this.a==null)E.e("Skipping cookie creation: no cookie info");else if(this.b==null)E.o("Skipping cookie creation: no cookie value");
else{var b=new Date;b.setTime(1000*this.a._expires_);var a=this.a._domain_,c=this.f+this.b+"; expires="+b.toGMTString()+"; path="+this.a._path_+"; domain=."+a;document.cookie=c;E.c("Written cookie: "+c)}};window.IDICommon=window.IDICommon||(function(){return{getHash:function(b){var a=b.indexOf("#")+1;return a?b.substr(a):""},htmlEscape:function(b){return/[&<>\"]/.test(b)?b.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;"):b},makeIframeTag:function(b){var a="<iframe";for(var c in b)a+=" "+c+'="'+IDICommon.htmlEscape(b[c])+'"';return a+"></iframe>"},getIframe:function(b,a){try{return b.frames[a]}catch(c){return null}},makeIframeNode:function(b){var a=document.createElement("iframe");
for(var c in b)a.setAttribute(c,b[c]);return a},appendHiddenIframe:function(b,a){setTimeout(function(){document.body.appendChild(IDICommon.makeIframeNode({id:b,name:b,src:a,width:0,height:0,frameBorder:0}))},0)},writeHiddenIframe:function(b,a){document.write(IDICommon.makeIframeTag({id:b,name:b,src:a,width:0,height:0,frameBorder:0}))},splitURIComponent:function(b,a){var c=[],e=b.length,d=0;while(d<e){var g=b.substr(d,a),i=g.length;if(d+i<e)for(var o=1;o<3;++o)if(g.charAt(i-o)=="%")g=g.substr(0,i-=
o);c.push(g);d+=i}return c},MAX_URL_LENGTH:4095,IDI_DEFAULT_POLLING_INTERVAL:1000}})();window.IDIHost=window.IDIHost||(function(){var b=window.location.href.replace(/([^:\/])\/.*$/,"$1/robots.txt"),a="",c={},e={},d={},g={},i={};function o(h,k){for(var p in k)h[p]=k[p]}function v(h,k){var p=window.frames[h];if(p){var x;while(x=IDICommon.getIframe(p,h+"_"+c[h])){try{if(x.location.href=="about:blank")break}catch(t){break}d[h]+=IDICommon.getHash(x.location.href);++c[h]}var q=d[h].split("$"),y=q.length-1;if(y>0){d[h]=q[y];for(var z=0;z<y;++z)k(decodeURIComponent(q[z]),h)}}}function r(h){return a||
h.replace(/([^:\/]\/).*$/,"$1ig/idi_relay")}function m(h){window.clearInterval(i[h]);i[h]=0}function F(h){b=h}function N(h){a=h}function O(h,k,p){m(h);i[h]=window.setInterval(function(){v(h,k)},typeof p=="object"&&p.pollingInterval||IDICommon.IDI_DEFAULT_POLLING_INTERVAL)}function I(h,k,p){var x;if(typeof p=="object")x=p.moduleRelayUrl;var t=e[h];if(isNaN(t))throw new Error("Invalid module id");else{var q=typeof x=="string"?x:r(g[h]),y=encodeURIComponent(k)+"$",z=IDICommon.MAX_URL_LENGTH-1-q.length,
C=IDICommon.splitURIComponent(y,z),P=C.length;for(var w=0;w<P;++w)IDICommon.appendHiddenIframe(h+"_"+(t+w),q+"#"+C[w]);e[h]+=P}}function J(h,k,p,x,t){var q={frameBorder:0,scrolling:"no"},y,z,C,P,w;if(typeof t=="object"){y=t.iframeAttrs;z=t.callback;C=t.userPrefs;P=t.pollingInterval;w=t.parentDivId}if(typeof y=="object")o(q,y);o(q,{id:k,name:k,src:h,width:p,height:x});c[k]=0;e[k]=0;d[k]="";g[k]=h;var Q=[];if(typeof C=="object")for(var D in C)Q.push(encodeURIComponent(D)+"="+encodeURIComponent(C[D]));
if(typeof z=="function"){Q.push("idi_hr="+encodeURIComponent(b));window.IDIHost.registerListener(k,z,t)}if(Q.length){var K=Q.join("&");if(q.src.length+1+K.length>IDICommon.MAX_URL_LENGTH){K+="$";var $=r(h),ka=IDICommon.MAX_URL_LENGTH-1-$.length,aa=IDICommon.splitURIComponent(K,ka),ba=aa.length;for(var D=0;D<ba;++D){var U=k+"_"+D,ca=$+"#"+aa[D];if(w){var V=document.getElementById(w);V.innerHTML+=IDICommon.makeIframeTag({id:U,name:U,src:ca,width:0,height:0,frameBorder:0})}else IDICommon.writeHiddenIframe(U,
ca)}e[k]+=ba;K=""}q.src+="#"+K}if(w){var V=document.getElementById(w);V.innerHTML+=IDICommon.makeIframeTag(q)}else document.write(IDICommon.makeIframeTag(q))}return{setHostRelayUrl:F,setModuleRelayUrl:N,getModuleRelayUrl:r,registerListener:O,unregisterListener:m,postMessageToModule:I,createModule:J}})();function L(b){return b!=null?'"'+b+'"':'""'}function H(b){return typeof encodeURIComponent=="function"?encodeURIComponent(b):escape(b)}function M(b,a){if(b&&a)window.google_ad_url+="&"+b+"="+a}function R(b){var a=window,c=A(b),e=a[b];M(c,e)}function S(b,a){if(a)M(b,H(a))}function T(b){var a=window,c=A(b),e=a[b];S(c,e)}function W(b,a){var c=window,e=A(b),d=c[b];if(e&&d&&typeof d=="object")d=d[a%d.length];M(e,d)}function ga(b,a){var c=b.screen,e=navigator.javaEnabled(),d=-a.getTimezoneOffset();if(c){M("u_h",
c.height);M("u_w",c.width);M("u_ah",c.availHeight);M("u_aw",c.availWidth);M("u_cd",c.colorDepth)}M("u_tz",d);M("u_his",history.length);M("u_java",e);if(navigator.plugins)M("u_nplug",navigator.plugins.length);if(navigator.mimeTypes)M("u_nmime",navigator.mimeTypes.length)}function ha(b){if(!b.google_enable_first_party_cookie)return;if(E==null)E=new B;if(b._GA_googleCookieHelper==null)b._GA_googleCookieHelper=new G;if(!b._google_cookie_fetched){b._google_cookie_fetched=true;b._GA_googleCookieHelper.j(X(b.google_ad_client))}}
function X(b){if(b){b=b.toLowerCase();if(b.substring(0,3)!="ca-")b="ca-"+b}return b}function ia(b){if(b){b=b.toLowerCase();if(b.substring(0,9)!="dist-aff-")b="dist-aff-"+b}return b}function ja(b,a){var c=document.getElementById(b);c.style.height=a+"px"}function la(b,a,c){window.clearTimeout(c);var e=/^google_resize_flash_ad_idi\((\d+)\)/,d=b.match(e);if(d)ja(a,d[1])}function ma(b,a,c,e){c=c.substring(0,2000);c=c.replace(/%\w?$/,"");if((b.google_ad_output=="js"||b.google_ad_output=="json_html")&&(b.google_ad_request_done||
b.google_radlink_request_done))a.write('<script language="JavaScript1.1" src='+L(c)+"><\/script>");else if(b.google_ad_output=="html"){if(b.name!="google_ads_frame"){if(e!=null)a.write('<div id="'+e+'">');if(na(b.google_ad_output,b.google_ad_client)){IDIHost.setModuleRelayUrl("http://pagead2.googlesyndication.com/pagead/idi_relay.html");var d=0;if(b.google_num_0ad_slots)d+=b.google_num_0ad_slots;if(b.google_num_ad_slots)d+=b.google_num_ad_slots;if(b.google_num_sdo_slots)d+=b.google_num_sdo_slots;
var g="google_inline_div"+d,i="<div id="+L(g)+' style="position:relative;width:'+b.google_ad_width+'px"></div><div style="position:relative;width:'+b.google_ad_width+"px;height:"+b.google_ad_height+'px;z-index:-1"></div>';a.write(i);var o="google_frame"+d,v=b.setTimeout(function(){IDIHost.unregisterListener(o)},5000);IDIHost.createModule(c,o,b.google_ad_width,b.google_ad_height,{callback:function(r,m){la(r,m,v)},pollingInterval:500,iframeAttrs:{style:"position: absolute;left:0px",marginWidth:"0",
marginHeight:"0",vspace:"0",hspace:"0",allowTransparency:"true"},parentDivId:g})}else{a.write('<iframe name="google_ads_frame" width='+L(b.google_ad_width)+" height="+L(b.google_ad_height)+" frameborder="+L(b.google_ad_frameborder)+" src="+L(c)+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">');a.write("</iframe>")}if(e!=null)a.write("</div>")}}else if(b.google_ad_output=="textlink")a.write('<script language="JavaScript1.1" src='+L(c)+"><\/script>")}
function oa(b){for(var a in s)b[a]=null;for(var a in u){if(a=="google_correlator")continue;b[a]=null}}function pa(b){if(b.google_ad_format)return b.google_ad_format.indexOf("_0ads")>0;return b.google_ad_output!="html"&&b.google_num_radlinks>0}function Y(b){return b&&b.indexOf("_sdo")!=-1}function qa(){var b=null,a=window,c=document,e=new Date,d=e.getTime(),g=a.google_ad_format;if(a.google_cpa_choice!=b){a.google_ad_url="http://pagead2.googlesyndication.com/cpa/ads?";a.google_ad_url+="client="+escape(X(a.google_ad_client));
a.google_ad_region="_google_cpa_region_";R("google_cpa_choice");if(typeof c.characterSet!="undefined")S("oe",c.characterSet);else if(typeof c.charset!="undefined")S("oe",c.charset)}else if(Y(g)){a.google_ad_url="http://pagead2.googlesyndication.com/pagead/sdo?";a.google_ad_url+="client="+escape(ia(a.google_ad_client))}else{a.google_ad_url="http://pagead2.googlesyndication.com/pagead/ads?";a.google_ad_url+="client="+escape(X(a.google_ad_client))}R("google_ad_host");R("google_ad_host_tier_id");var i=
a.google_num_slots_by_client,o=a.google_num_slots_by_channel,v=a.google_prev_ad_formats_by_region,r=a.google_prev_ad_slotnames_by_region;if(a.google_ad_region==b&&a.google_ad_section!=b)a.google_ad_region=a.google_ad_section;var m=a.google_ad_region==b?"":a.google_ad_region;if(Y(g)){a.google_num_sdo_slots=a.google_num_sdo_slots?a.google_num_sdo_slots+1:1;if(a.google_num_sdo_slots>4)return false}else if(pa(a)){a.google_num_0ad_slots=a.google_num_0ad_slots?a.google_num_0ad_slots+1:1;if(a.google_num_0ad_slots>
3)return false}else if(a.google_cpa_choice==b){a.google_num_ad_slots=a.google_num_ad_slots?a.google_num_ad_slots+1:1;if(a.google_num_slots_to_rotate){v[m]=b;r[m]=b;if(a.google_num_slot_to_show==b)a.google_num_slot_to_show=d%a.google_num_slots_to_rotate+1;if(a.google_num_slot_to_show!=a.google_num_ad_slots)return false}else if(a.google_num_ad_slots>6&&m=="")return false}M("dt",e.getTime());R("google_language");if(a.google_country)R("google_country");else R("google_gl");R("google_region");T("google_city");
T("google_hints");R("google_safe");R("google_encoding");R("google_last_modified_time");T("google_alternate_ad_url");R("google_alternate_color");R("google_skip");R("google_targeting");var F=a.google_ad_client;if(!i[F]){i[F]=1;i.length+=1}else i[F]+=1;if(v[m])if(!Y(g)){S("prev_fmts",v[m].toLowerCase());if(i.length>1)M("slot",i[F])}if(r[m])S("prev_slotnames",r[m].toLowerCase());if(g&&!a.google_ad_slot){S("format",g.toLowerCase());if(!Y(g))v[m]=v[m]?v[m]+","+g:g}if(a.google_ad_slot)r[m]=r[m]?r[m]+","+
a.google_ad_slot:a.google_ad_slot;R("google_max_num_ads");M("output",a.google_ad_output);R("google_adtest");R("google_ad_callback");R("google_ad_slot");T("google_correlator");if(a.google_ad_channel){T("google_ad_channel");var N="",O=a.google_ad_channel.split(/[+, ]/);for(var I=0;I<O.length;I++){var J=O[I];if(!o[J])o[J]=1;else N+=J+"+"}S("pv_ch",N)}if(a.google_enable_first_party_cookie)S("cookie",a._GA_googleCookieHelper.l());T("google_page_url");W("google_color_bg",d);W("google_color_text",d);W("google_color_link",
d);W("google_color_url",d);W("google_color_border",d);W("google_color_line",d);if(a.google_reuse_colors)M("reuse_colors",1);else M("reuse_colors",0);R("google_kw_type");T("google_kw");T("google_contents");R("google_num_radlinks");R("google_max_radlink_len");R("google_rl_filtering");R("google_rl_mode");R("google_rt");T("google_rl_dest_url");R("google_num_radlinks_per_unit");R("google_ad_type");R("google_image_size");R("google_ad_region");R("google_feedback");T("google_referrer_url");T("google_page_location");
M("frm",a.google_iframing);R("google_bid");R("google_cust_age");R("google_cust_gender");R("google_cust_interests");R("google_cust_id");R("google_cust_job");R("google_cust_u_url");R("google_cust_l");R("google_cust_lh");R("google_cust_ch");R("google_ed");T("google_ui_features");T("google_only_ads_with_video");T("google_disable_video_autoplay");if(ra(a,c)&&c.body){var h=c.body.scrollHeight,k=c.body.clientHeight;if(k&&h)S("cc",Math.round(k*100/h))}da();M("ga_vid",a.gaGlobal.vid);M("ga_sid",a.gaGlobal.sid);
M("ga_hid",a.gaGlobal.hid);M("ga_fc",a.gaGlobal.from_cookie);T("google_analytics_uacct");R("google_ad_override");R("google_flash_version");ga(a,e);return true}function sa(){var b=window,a=document;ha(b);if(!qa())return;ma(b,a,b.google_ad_url,null);oa(b)}function ta(){sa();return true}function ra(b,a){return b.top.location==a.location}function ua(b,a){var c=a.documentElement;if(ra(b,a))return false;if(b.google_ad_width&&b.google_ad_height){var e=1,d=1;if(b.innerHeight){e=b.innerWidth;d=b.innerHeight}else if(c&&
c.clientHeight){e=c.clientWidth;d=c.clientHeight}else if(a.body){e=a.body.clientWidth;d=a.body.clientHeight}if(d>2*b.google_ad_height||e>2*b.google_ad_width)return false}return true}function va(b){var a=window,c=null,e=a.onerror;a.onerror=b;if(a.google_ad_frameborder==c)a.google_ad_frameborder=0;if(a.google_ad_output==c)a.google_ad_output="html";if(Y(a.google_ad_format)){var d=a.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(d){a.google_ad_width=parseInt(d[1],10);a.google_ad_height=parseInt(d[2],10);
a.google_ad_output="html"}}if(a.google_ad_format==c&&a.google_ad_output=="html")a.google_ad_format=a.google_ad_width+"x"+a.google_ad_height;wa(a,document);if(a.google_num_slots_by_channel==c)a.google_num_slots_by_channel=[];if(a.google_num_slots_by_client==c)a.google_num_slots_by_client=[];if(a.google_prev_ad_formats_by_region==c)a.google_prev_ad_formats_by_region=[];if(a.google_prev_ad_slotnames_by_region==c)a.google_prev_ad_slotnames_by_region=[];if(a.google_correlator==c)a.google_correlator=(new Date).getTime();
if(a.google_adslot_loaded==c)a.google_adslot_loaded={};if(a.google_adContentsBySlot==c)a.google_adContentsBySlot={};if(a.google_flash_version==c)a.google_flash_version=xa();a.onerror=e}function ya(b){if(b in Z)return Z[b];return Z[b]=navigator.userAgent.toLowerCase().indexOf(b)!=-1}var Z={};function na(b,a){if(b!="html")return false;var c={};c["ca-pub-7027491298716603"]=true;c["ca-pub-8344185808443527"]=true;c["ca-pub-9812682548211238"]=true;c["ca-pub-4424308218891706"]=true;c["ca-pub-6922559858235084"]=
true;c["ca-pub-6477563040863705"]=true;c["ca-google"]=true;return c[X(a)]!=null}function za(b){var a={},c=b.split("?"),e=c[c.length-1].split("&");for(var d=0;d<e.length;d++){var g=e[d].split("=");if(g[0])try{a[g[0].toLowerCase()]=g.length>1?(window.decodeURIComponent?decodeURIComponent(g[1].replace(/\+/g," ")):unescape(g[1])):""}catch(i){}}return a}function Aa(){var b=window,a=za(document.URL);if(a.google_ad_override){b.google_ad_override=a.google_ad_override;b.google_adtest="on"}}function xa(){if(navigator.plugins&&
navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];if(b&&b.description)return b.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var a=3,c=1;while(c)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(e){c=null}return a.toString()}else if(ya("msie")&&!window.opera){var c=null;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){var a=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
a=6;c.AllowScriptAccess="always"}catch(e){if(a==6)return a.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(e){}}if(c!=null){var a=c.GetVariable("$version").split(" ")[1];return a.replace(/,/g,".")}}return"0"}function Ba(b,a){for(var c in a)b["google_"+c]=a[c]}function Ca(b,a){if(!a)return b.location;return b.referrer}function Da(b,a){if(!a&&b.google_referrer_url==null)return"0";else if(a&&b.google_referrer_url==null)return"1";else if(!a&&b.google_referrer_url!=null)return"2";
else if(a&&b.google_referrer_url!=null)return"3";return"4"}function Ea(b,a,c,e){b.page_url=Ca(c,e);b.page_location=null}function Fa(b,a,c,e){b.page_url=a.google_page_url;b.page_location=Ca(c,e)||"EMPTY"}function Ga(b,a){var c={},e=ua(b,a);c.iframing=Da(b,e);if(!(!b.google_page_url))Fa(c,b,a,e);else Ea(c,b,a,e);c.last_modified_time=a.location==c.page_url?Date.parse(a.lastModified)/1000:null;c.referrer_url=e?b.google_referrer_url:(b.google_page_url&&b.google_referrer_url?b.google_referrer_url:a.referrer);
return c}function Ha(b){var a={},c=b.URL.substring(b.URL.lastIndexOf("http"));a.iframing=null;a.page_url=c;a.page_location=b.location;a.last_modified_time=null;a.referrer_url=c;return a}function wa(b,a){var c;c=b.google_page_url==null&&Ia[a.domain]?Ha(a):Ga(b,a);Ba(b,c)}var Ia={};Ia["ad.yieldmanager.com"]=true;Aa();va(ta);sa();
})()
